"""
02_sampling.py
==============
Generates a stratified sample of 3,000 comments from the full corpus
for human annotation on Prolific.

Sampling criteria:
  - Quality filters: length between 80-800 chars, >= 5 words,
    no URLs in text, target description with real text
  - Deduplication by (topic, text) pairs
  - Only topics with >= 10 quality comments
  - Proportional sampling by topic size:
      slots = clamp(round(n_qualifying * RATE), MIN_SLOTS, MAX_SLOTS)
  - Length diversity within each topic (short/medium/long)

INPUT:
    - corpus_stance_madrid_recuento.csv  (generated by 01_build_corpus.py)

OUTPUT:
    - corpus_final_decide_madrid.csv  (3,000 samples, columns: id, target,
      description, comment)

USAGE:
    python 02_sampling.py <path_to_corpus_stance_madrid_recuento.csv>
"""

import os
import sys
import math
import re

import pandas as pd
import yaml

sys.stdout.reconfigure(encoding='utf-8')

script_dir = os.path.dirname(os.path.abspath(__file__))
root_dir   = os.path.dirname(script_dir)

config_path = os.path.join(root_dir, 'config.yaml')
with open(config_path, 'r', encoding='utf-8') as f:
    cfg = yaml.safe_load(f)

SAMPLING = cfg['sampling']
PATHS    = cfg['paths']

if len(sys.argv) > 1:
    csv_path = sys.argv[1]
else:
    csv_path = os.path.join(root_dir, PATHS['corpus_input'])

out_path = os.path.join(root_dir, PATHS['corpus_output'])

# -- Load corpus --
print("Loading corpus...")
df = pd.read_csv(csv_path, encoding=PATHS['csv_encoding'], low_memory=False)
df['len_com'] = df['Texto (Opinion)'].str.len()
print(f"  Total: {len(df):,} comments, {df['Target (Tema)'].nunique():,} topics")

# -- Quality filters on comments --
url_in_text = df['Texto (Opinion)'].str.contains(r'https?://', regex=True, na=False)

def desc_without_url_is_short(desc):
    if pd.isna(desc):
        return True
    text_no_url = re.sub(r'https?://\S+', '', str(desc)).strip()
    return len(text_no_url) < SAMPLING['min_desc_chars_no_url']

desc_is_basically_url = df['Descripcion Target'].apply(desc_without_url_is_short)

length_ok  = df['len_com'].between(SAMPLING['min_chars'], SAMPLING['max_chars'])
words_ok   = df['Texto (Opinion)'].str.split().str.len() >= SAMPLING['min_words']

df_q = df[~url_in_text & ~desc_is_basically_url & length_ok & words_ok].copy()
print(f"  After quality filters: {len(df_q):,} comments, "
      f"{df_q['Target (Tema)'].nunique():,} topics")

# -- Deduplicate by (topic, text) --
n_before_dedup = len(df_q)
df_q = df_q.drop_duplicates(subset=['Target (Tema)', 'Texto (Opinion)']).copy()
n_dedup = n_before_dedup - len(df_q)
print(f"  After deduplication (same topic+text): {len(df_q):,} comments "
      f"(-{n_dedup:,} duplicates removed)")

# -- Statistics by topic and filter out small topics --
topic_counts = df_q.groupby('Target (Tema)')['Texto (Opinion)'].count()
valid_topics = topic_counts[topic_counts >= SAMPLING['min_topic_comments']].index
df_v = df_q[df_q['Target (Tema)'].isin(valid_topics)].copy()
print(f"  Topics with >={SAMPLING['min_topic_comments']} quality comments: {len(valid_topics):,}")
print(f"  Comments in those topics: {len(df_v):,}")

# -- Sampling function per topic --
def sample_topic(group, n_slots, seed=SAMPLING['random_seed']):
    g = group.copy()
    chosen_idx = set()

    bands = pd.cut(g['len_com'], bins=SAMPLING['length_bins'],
                   labels=['short', 'medium', 'long'])
    g['_band'] = bands

    for band in ['short', 'medium', 'long']:
        if len(chosen_idx) >= n_slots:
            break
        sub = g[(g['_band'] == band) & (~g.index.isin(chosen_idx))]
        if len(sub) > 0:
            idx = sub.sample(1, random_state=seed).index[0]
            chosen_idx.add(idx)

    remaining = n_slots - len(chosen_idx)
    if remaining > 0:
        pool = g[~g.index.isin(chosen_idx)]
        n_fill = min(remaining, len(pool))
        if n_fill > 0:
            extra = pool.sample(n_fill, random_state=seed).index
            chosen_idx.update(extra)

    return g.loc[list(chosen_idx)].drop(columns=['_band'], errors='ignore')

# -- Proportional sampling --
print(f"\nSampling with RATE={SAMPLING['rate']}, "
      f"MIN_SLOTS={SAMPLING['min_slots']}, MAX_SLOTS={SAMPLING['max_slots']}...")

parts = []
slots_per_topic = {}
selected_idx = set()
for topic, group in df_v.groupby('Target (Tema)'):
    n_q = len(group)
    n_slots = int(min(max(round(n_q * SAMPLING['rate']), SAMPLING['min_slots']), SAMPLING['max_slots']))
    slots_per_topic[topic] = n_slots
    selection = sample_topic(group, n_slots)
    selected_idx.update(selection.index)
    parts.append(selection)

sample = pd.concat(parts, ignore_index=True)
print(f"  Sample before adjustment: {len(sample):,} comments from "
      f"{sample['Target (Tema)'].nunique():,} topics")

# Adjust to the target total
if len(sample) > SAMPLING['target_total']:
    excess = len(sample) - SAMPLING['target_total']
    sample_counts = sample['Target (Tema)'].value_counts()
    idx_remove = set()
    for topic in sample_counts.index:
        if excess <= 0:
            break
        candidates = sample[sample['Target (Tema)'] == topic].index.tolist()
        if len(candidates) > SAMPLING['min_slots']:
            remove = sample.loc[candidates].sample(1, random_state=SAMPLING['random_seed']).index
            idx_remove.update(remove)
            excess -= 1
    sample = sample.drop(index=list(idx_remove))

elif len(sample) < SAMPLING['target_total']:
    missing = SAMPLING['target_total'] - len(sample)
    print(f"  Sample below target by {missing} -- filling...")
    reserve_parts = []
    for topic, group in df_v.groupby('Target (Tema)'):
        pool = group[~group.index.isin(selected_idx)]
        if len(pool) > 0:
            reserve_parts.append((topic, len(pool), pool))
    reserve_parts.sort(key=lambda x: x[1], reverse=True)
    extras = []
    for topic, _, pool in reserve_parts:
        if missing <= 0:
            break
        n_extra = min(missing, len(pool))
        extra = pool.sample(n_extra, random_state=SAMPLING['random_seed'])
        extras.append(extra)
        selected_idx.update(extra.index)
        missing -= n_extra
    if extras:
        sample = pd.concat([sample] + extras, ignore_index=True)

# Sort by topic
sample = sample.sort_values('Target (Tema)', kind='stable').reset_index(drop=True)

# -- Output columns (simplified for annotation) --
sample_out = pd.DataFrame({
    'id': range(1, len(sample) + 1),
    'target': sample['Target (Tema)'].values,
    'description': sample['Descripcion Target'].values,
    'comment': sample['Texto (Opinion)'].values,
})

os.makedirs(os.path.dirname(out_path), exist_ok=True)
sample_out.to_csv(out_path, index=False, sep=PATHS['csv_separator'], encoding=PATHS['csv_encoding'])

# -- Summary --
print(f"\n{'='*60}")
print(f"FINAL SAMPLE: {len(sample_out):,} comments")
print(f"Unique topics:  {sample_out['target'].nunique():,}")
print(f"\nSaved to: {out_path}")
